name: ci

on:
  pull_request:
    branches: 
      - 'master'
      - 'release'

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Extract Repo Name Lowercase
        shell: bash
        run: echo "##[set-output name=repo;]$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"
        id: extract_repo
      
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PAT }}
      -
        name: Only Build on PRs
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: false
          tags: |
            ghcr.io/${{ steps.extract_repo.outputs.repo }}

